Better progress reporting
simon-friedberger/dap-random-client pull request #3
Opened 2023-11-15 22:12 UTC by ncloudioj

Was noticing some clunky logging in the console when trying to test bulk submission (for load testing). This adds a progress report that makes it easier to read.  
```
Submitting reports: [・・・・・・・・・Co o o o o ] 75%
```

2023-11-15 22:14 UTC, simon-friedberger requested changes
Please use more emojis.

2023-11-15 23:40 UTC, ncloudioj commented
![pacman](https://github.com/simon-friedberger/dap-random-client/assets/1455254/6d797e80-1089-4244-ac4d-78166f2257da)

Nope, Pacman wins. Take it or leave it. 😠

2023-11-16 08:47 UTC, simon-friedberger commented
Are you sure?
`ᗧ···ᗣ···ᗣ··`

2023-11-16 13:30 UTC, ncloudioj commented
Oh my, such a genius. Questionable move though, pacman will die going that direction.

2023-11-16 13:32 UTC, simon-friedberger commented
`ᗧ···🍒···🍒··`

2023-11-16 13:40 UTC, ncloudioj commented
Okay, you win! 💯 
Well, for small batch submissions, the progress bar was barely visible. Forget about it and I will close it, just some fun to play Pacman.

2023-11-16 13:41 UTC, simon-friedberger commented
Don't you dare!

2023-11-16 13:41 UTC, merged